server:
  applicationContextPath: /Main/v1
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081


dataSourceFactory:
  driverClass: org.mariadb.jdbc.Driver
  url: jdbc:mariadb://localhost:3306/student_db
  user: root
  password: MyNewPass
  properties:
    hibernate.dialect: org.hibernate.dialect.MariaDBDialect

